[versions]
agp = "7.3.1"
kotlin = "1.8.22"
mavenPublish = "0.25.3"
composeCompiler = "1.4.8"
robolectric = "4.10.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.7.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.1" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material = { module = "androidx.compose.material:material", version = "1.4.2" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version = "1.0.1" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.3" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }