[versions]
agp = "7.3.1"
kotlin = "1.8.22"
mavenPublish = "0.25.3"
composeCompiler = "1.4.8"
robolectric = "4.10.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.7.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.1" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }